version: "3.7"
services:
  redis:
    image: redis:5.0
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data
    networks:
      ducatus_alerts_net:
    container_name: ducatus_alerts_redis
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src/:/code/src/
      - ./logs/:/code/logs/
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      ducatus_alerts_net:
    container_name: ducatus_alerts_bot
    command: python3 start_bot_polling.py
  checker:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src/:/code/src/
      - ./logs/:/code/logs/
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      ducatus_alerts_net:
    container_name: ducatus_alerts_checker
    command: python3 start_checkers.py

networks:
  ducatus_alerts_net:
