version: "3.7"
services:
  db:
    image: mongo:5.0.19-rc0
    restart: unless-stopped
    env_file:
      - ./.env
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./dumps/:/dumps/
      - ./.docker/mongodb:/data/db
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src/:/code/src/
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      ducatus_alerts_net:
    container_name: ducatus_alerts_main

networks:
  ducatus_alerts_net:
